/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 05:08:26 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.HeapSort;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HeapSort_ESTest extends HeapSort_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      String[] stringArray0 = new String[3];
      stringArray0[0] = "C/3,?&C#Uf6}8)f7\"m*";
      stringArray0[1] = "";
      stringArray0[2] = ":$%";
      HeapSort.main(stringArray0);
      int[] intArray0 = new int[1];
      intArray0[0] = 3;
      heapSort0.maxHeapify(intArray0, 3);
      heapSort0.buildMaxHeap(intArray0);
      heapSort0.maxHeapifyForSort(intArray0, 3, 3);
      int[] intArray1 = new int[1];
      intArray1[0] = 1414;
      heapSort0.maxHeapifyForSort(intArray1, 2389, 6);
      heapSort0.buildMaxHeap(intArray1);
      heapSort0.buildMaxHeap(intArray1);
      int[] intArray2 = new int[9];
      intArray2[0] = 2389;
      intArray2[1] = 6;
      String[] stringArray1 = new String[2];
      stringArray1[0] = "TNQ>.(S(*`Z`Z]f\"H";
      stringArray1[1] = "TNQ>.(S(*`Z`Z]f\"H";
      HeapSort.main(stringArray1);
      HeapSort.main(stringArray1);
      intArray2[2] = (-2775);
      intArray2[4] = 1414;
      intArray2[6] = 6;
      intArray2[7] = 6;
      intArray2[8] = 1414;
      // Undeclared exception!
      try { 
        heapSort0.maxHeapifyForSort(intArray2, 3, 1414);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 13
         //
         assertThrownBy("edu.osu.cs362.HeapSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      int[] intArray0 = new int[7];
      intArray0[0] = (-254);
      intArray0[1] = (-1);
      intArray0[2] = (-2780);
      String[] stringArray0 = new String[4];
      stringArray0[0] = "KEQm>4'6]ii$FdhVu~";
      stringArray0[1] = "Tk{8^e(ij\"4^Dw";
      stringArray0[2] = "XB";
      stringArray0[3] = "After Sorting Array : ";
      HeapSort.main(stringArray0);
      intArray0[3] = 69;
      intArray0[4] = 1;
      intArray0[5] = 1;
      intArray0[6] = 766;
      heapSort0.buildMaxHeap(intArray0);
      int[] intArray1 = new int[2];
      intArray1[0] = 1;
      intArray1[1] = (-1);
      // Undeclared exception!
      try { 
        heapSort0.maxHeapifyForSort(intArray1, 1, 19);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         assertThrownBy("edu.osu.cs362.HeapSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      int[] intArray0 = new int[1];
      intArray0[0] = 3;
      heapSort0.maxHeapify(intArray0, 3);
      heapSort0.buildMaxHeap(intArray0);
      heapSort0.maxHeapifyForSort(intArray0, 3, 3);
      int[] intArray1 = new int[1];
      intArray1[0] = 1414;
      heapSort0.maxHeapifyForSort(intArray1, 2389, 6);
      heapSort0.buildMaxHeap(intArray1);
      heapSort0.buildMaxHeap(intArray1);
      int[] intArray2 = new int[9];
      intArray2[0] = 2389;
      intArray2[1] = 6;
      String[] stringArray0 = new String[2];
      stringArray0[0] = "TNQ>.(S(*`Z`Z]f\"H";
      stringArray0[1] = "?#pONK['kkz/P*8QS";
      HeapSort.main(stringArray0);
      HeapSort.main(stringArray0);
      intArray2[2] = (-2775);
      intArray2[3] = 1414;
      intArray2[4] = 1414;
      intArray2[5] = 1414;
      intArray2[6] = 6;
      intArray2[7] = 6;
      intArray2[8] = 1414;
      // Undeclared exception!
      try { 
        heapSort0.maxHeapifyForSort(intArray2, 3, 1414);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 11
         //
         assertThrownBy("edu.osu.cs362.HeapSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      heapSort0.getLeft(143);
      String[] stringArray0 = new String[5];
      stringArray0[0] = "Original Array : ";
      stringArray0[1] = "";
      stringArray0[2] = "t";
      stringArray0[3] = "NGIc?>R!NzEn]xJ^bIY";
      stringArray0[4] = "";
      HeapSort.main(stringArray0);
      HeapSort.main(stringArray0);
      String[] stringArray1 = new String[9];
      stringArray1[0] = "NGIc?>R!NzEn]xJ^bIY";
      stringArray1[1] = "SsVT-X$ R|%}}h%Vw";
      stringArray1[2] = "NGIc?>R!NzEn]xJ^bIY";
      stringArray1[3] = "t";
      stringArray1[4] = "";
      stringArray1[5] = "";
      stringArray1[6] = "NGIc?>R!NzEn]xJ^bIY";
      stringArray1[7] = "";
      stringArray1[8] = "t";
      HeapSort.main(stringArray1);
      heapSort0.getParent(1768);
      // Undeclared exception!
      try { 
        heapSort0.maxHeapifyForSort((int[]) null, 7, 884);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.HeapSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      int[] intArray0 = new int[6];
      intArray0[0] = 1;
      HeapSort.main((String[]) null);
      intArray0[1] = 14;
      intArray0[2] = 2410;
      HeapSort.main((String[]) null);
      intArray0[3] = 1396;
      HeapSort.main((String[]) null);
      HeapSort.main((String[]) null);
      intArray0[4] = 15;
      intArray0[5] = 0;
      heapSort0.heapSort(intArray0);
      heapSort0.maxHeapify(intArray0, 1);
      heapSort0.heapSort(intArray0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      heapSort0.getParent((-2269));
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      heapSort0.getLeft(0);
      HeapSort heapSort1 = new HeapSort();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      heapSort0.getParent(14);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "";
      stringArray0[1] = "wD";
      stringArray0[2] = "]B(Ju";
      stringArray0[3] = "";
      HeapSort.main(stringArray0);
      HeapSort.main((String[]) null);
      HeapSort.main((String[]) null);
      HeapSort.main((String[]) null);
      HeapSort.main((String[]) null);
      HeapSort.main((String[]) null);
      // Undeclared exception!
      try { 
        heapSort0.maxHeapify((int[]) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.HeapSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "";
      HeapSort.main(stringArray0);
      stringArray0[1] = "Z+dnT\"F^5~K2";
      stringArray0[2] = "";
      HeapSort.main(stringArray0);
      stringArray0[3] = "|?6C2q";
      HeapSort.main(stringArray0);
      HeapSort.main(stringArray0);
      heapSort0.getLeft(2937);
      // Undeclared exception!
      try { 
        heapSort0.heapSort((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.HeapSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      String[] stringArray0 = new String[0];
      HeapSort.main(stringArray0);
      heapSort0.getParent(0);
      int[] intArray0 = new int[1];
      intArray0[0] = 0;
      heapSort0.swap(intArray0, 0, 0);
      heapSort0.getRight(428);
      heapSort0.heapSort(intArray0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      HeapSort.main((String[]) null);
      int[] intArray0 = new int[4];
      HeapSort.main((String[]) null);
      intArray0[0] = 0;
      intArray0[1] = 4;
      intArray0[2] = 9;
      intArray0[3] = 0;
      heapSort0.maxHeapify(intArray0, 2551);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        heapSort0.maxHeapifyForSort(intArray0, 0, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         assertThrownBy("edu.osu.cs362.HeapSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      heapSort0.getRight(1);
      int[] intArray0 = new int[4];
      intArray0[0] = 3;
      intArray0[1] = 1;
      intArray0[2] = 1;
      intArray0[3] = 1;
      heapSort0.maxHeapify(intArray0, 1);
      heapSort0.maxHeapifyForSort(intArray0, 3, 3);
      // Undeclared exception!
      try { 
        heapSort0.swap(intArray0, (-3656), 1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      int[] intArray0 = new int[2];
      intArray0[0] = 0;
      intArray0[1] = 0;
      // Undeclared exception!
      try { 
        heapSort0.maxHeapify(intArray0, 0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         assertThrownBy("edu.osu.cs362.HeapSort", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "2/$lppu3XhmWFKrve/#";
      HeapSort.main(stringArray0);
      heapSort0.getLeft(6);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      int[] intArray0 = new int[6];
      intArray0[0] = (-1391);
      intArray0[1] = 0;
      intArray0[2] = 0;
      intArray0[3] = 0;
      intArray0[4] = 0;
      intArray0[5] = (-3849);
      heapSort0.heapSort(intArray0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      int[] intArray0 = new int[3];
      intArray0[0] = 0;
      intArray0[2] = 10;
      heapSort0.heapSort(intArray0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      heapSort0.getParent(0);
      int[] intArray0 = new int[3];
      intArray0[0] = 0;
      intArray0[1] = 0;
      intArray0[2] = 0;
      heapSort0.buildMaxHeap(intArray0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      // Undeclared exception!
      try { 
        heapSort0.swap((int[]) null, 2165, 2046);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "";
      HeapSort.main(stringArray0);
      int int0 = heapSort0.getLeft((-1));
      assertEquals((-2), int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      HeapSort heapSort0 = new HeapSort();
      heapSort0.getRight((-1));
      heapSort0.getParent((-1));
      HeapSort.main((String[]) null);
      // Undeclared exception!
      try { 
        heapSort0.buildMaxHeap((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.HeapSort", e);
      }
  }
}
